name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "RUNNER WORKS"
          hostname
          whoami
          pwd

      - name: Deploy
        run: |
          docker compose up -d --build
